### ISSUE TITLE
Can you add topics in this repository?

### ISSUE THREAD

**Issue by Neustradamus** [iwpnd/tile38-kafka-sasl#2]
@iwpnd: I wish you a Happy New Year!

Can you add in this repository, topics?
- scram
- scram-sha-512

Thanks in advance.

**Comment by iwpnd** [comment]
Happy new year to you too, @Neustradamus!

scram-sha-512 is what the example is about, I’m not sure what you want me to do. :)

**Comment by Neustradamus** [comment]
@iwpnd: Thanks too :)

Here: https://github.com/iwpnd/tile38-kafka-sasl/ at right, click on the gear in "About" section ^^

**Comment by iwpnd** [comment]
Aaah that's what you mean. Sure thing! Will do it once I’m at a computer! Thanks for the pointer :)

**Comment by iwpnd** [comment]
done, thanks for pointing it out :)

**Comment by Neustradamus** [comment]
@iwpnd: Thanks to you! :)
